### ISSUE TITLE
Need extra hands?

### ISSUE THREAD

**Issue by sand4rt** [preactjs/playwright-ct#4]
Hey, came across your library and was wondering if you guys can use some extra hands? I've been working on Playwright's component testing feature for the other frameworks and i can make sure everything is consistent? Perhaps we could advocate moving the adapter to Playwright's repository to combine efforts?

**Comment by JoviDeCroock** [comment]
That would be amazing, more than welcome! 😃

**Comment by sand4rt** [comment]
Awesome!:) Just created a PR to add some tests first.
